/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 341WB3S6fAjbZggAzyKhr1
// Component: fEg2J73XB5Qp

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { ForgotPassword } from "../../../plasmic-library/authentication/ForgotPassword"; // plasmic-import: el6iEZhK34im/codeComponent

import { useScreenVariants as useScreenVariantsjdkNhxaWnKvk } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: JdkNHXAWnKVK/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 341WB3S6fAjbZggAzyKhr1/projectcss
import sty from "./PlasmicForgotPassword.module.css"; // plasmic-import: fEg2J73XB5Qp/css

import Ellipse187Icon from "./icons/PlasmicIcon__Ellipse187"; // plasmic-import: HCPsunS-fmP6/icon
import Ellipse192Icon from "./icons/PlasmicIcon__Ellipse192"; // plasmic-import: RdQSueESMBau/icon

createPlasmicElementProxy;

export type PlasmicForgotPassword__VariantMembers = {};
export type PlasmicForgotPassword__VariantsArgs = {};
type VariantPropType = keyof PlasmicForgotPassword__VariantsArgs;
export const PlasmicForgotPassword__VariantProps = new Array<VariantPropType>();

export type PlasmicForgotPassword__ArgsType = {};
type ArgPropType = keyof PlasmicForgotPassword__ArgsType;
export const PlasmicForgotPassword__ArgProps = new Array<ArgPropType>();

export type PlasmicForgotPassword__OverridesType = {
  root?: Flex__<"div">;
  freeBox?: Flex__<"div">;
  logo?: Flex__<"div">;
  imageLogo?: Flex__<"div">;
  frame65?: Flex__<"div">;
  rectangle136?: Flex__<"div">;
  frame67?: Flex__<"div">;
  rectangle137?: Flex__<"div">;
  text?: Flex__<"div">;
  forgotPasswordForm?: Flex__<typeof ForgotPassword>;
};

export interface DefaultForgotPasswordProps {}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicForgotPassword__RenderFunc(props: {
  variants: PlasmicForgotPassword__VariantsArgs;
  args: PlasmicForgotPassword__ArgsType;
  overrides: PlasmicForgotPassword__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "forgotPasswordForm.email",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => ""
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariantsjdkNhxaWnKvk()
  });

  return (
    <React.Fragment>
      <Head>
        <meta name="twitter:card" content="summary" />
        <title key="title">{PlasmicForgotPassword.pageMetadata.title}</title>
        <meta
          key="og:title"
          property="og:title"
          content={PlasmicForgotPassword.pageMetadata.title}
        />
        <meta
          key="twitter:title"
          name="twitter:title"
          content={PlasmicForgotPassword.pageMetadata.title}
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={projectcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            projectcss.all,
            projectcss.root_reset,
            projectcss.plasmic_default_styles,
            projectcss.plasmic_mixins,
            projectcss.plasmic_tokens,
            plasmic_antd_5_hostless_css.plasmic_tokens,
            sty.root
          )}
        >
          <div
            data-plasmic-name={"freeBox"}
            data-plasmic-override={overrides.freeBox}
            className={classNames(projectcss.all, sty.freeBox)}
          >
            <div
              data-plasmic-name={"logo"}
              data-plasmic-override={overrides.logo}
              className={classNames(projectcss.all, sty.logo)}
            >
              <div
                data-plasmic-name={"imageLogo"}
                data-plasmic-override={overrides.imageLogo}
                className={classNames(projectcss.all, sty.imageLogo)}
              >
                <div
                  data-plasmic-name={"frame65"}
                  data-plasmic-override={overrides.frame65}
                  className={classNames(projectcss.all, sty.frame65)}
                >
                  <div
                    data-plasmic-name={"rectangle136"}
                    data-plasmic-override={overrides.rectangle136}
                    className={classNames(projectcss.all, sty.rectangle136)}
                  />
                </div>
                <div
                  data-plasmic-name={"frame67"}
                  data-plasmic-override={overrides.frame67}
                  className={classNames(projectcss.all, sty.frame67)}
                >
                  <div
                    data-plasmic-name={"rectangle137"}
                    data-plasmic-override={overrides.rectangle137}
                    className={classNames(projectcss.all, sty.rectangle137)}
                  />

                  <Ellipse187Icon
                    className={classNames(projectcss.all, sty.svg__tjYzw)}
                    role={"img"}
                  />

                  <Ellipse192Icon
                    className={classNames(projectcss.all, sty.svg__pYhn)}
                    role={"img"}
                  />
                </div>
              </div>
              <div
                data-plasmic-name={"text"}
                data-plasmic-override={overrides.text}
                className={classNames(
                  projectcss.all,
                  projectcss.__wab_text,
                  sty.text
                )}
              >
                {"Sitex"}
              </div>
            </div>
            <ForgotPassword
              data-plasmic-name={"forgotPasswordForm"}
              data-plasmic-override={overrides.forgotPasswordForm}
              buttonCancelStyle={"tertiary"}
              cancelButtonText={"Annuler"}
              className={classNames("__wab_instance", sty.forgotPasswordForm)}
              descriptionText={
                "Pas de panique, nous allons vous envoyer un e-mail pour vous aider à réinitialiser votre mot de passe."
              }
              email={generateStateValueProp($state, [
                "forgotPasswordForm",
                "email"
              ])}
              emailLabel={"Email"}
              inputStyle={"simple"}
              onEmailChange={async (...eventArgs: any) => {
                generateStateOnChangeProp($state, [
                  "forgotPasswordForm",
                  "email"
                ]).apply(null, eventArgs);
              }}
              onSubmit={async event => {
                const $steps = {};

                $steps["invokeGlobalAction"] = true
                  ? (() => {
                      const actionArgs = {
                        args: [
                          (() => {
                            try {
                              return $state.forgotPasswordForm.email;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return undefined;
                              }
                              throw e;
                            }
                          })()
                        ]
                      };
                      return $globalActions[
                        "SupabaseUserGlobalContext.resetPasswordForEmail"
                      ]?.apply(null, [...actionArgs.args]);
                    })()
                  : undefined;
                if (
                  $steps["invokeGlobalAction"] != null &&
                  typeof $steps["invokeGlobalAction"] === "object" &&
                  typeof $steps["invokeGlobalAction"].then === "function"
                ) {
                  $steps["invokeGlobalAction"] = await $steps[
                    "invokeGlobalAction"
                  ];
                }

                $steps["invokeGlobalAction2"] = true
                  ? (() => {
                      const actionArgs = {
                        args: [
                          "info",
                          "Si un compte est associ\u00e9 \u00e0 cet e-mail, vous recevrez un message pour r\u00e9initialiser votre mot de passe.",
                          undefined,
                          undefined,
                          "topRight"
                        ]
                      };
                      return $globalActions[
                        "plasmic-antd5-config-provider.showNotification"
                      ]?.apply(null, [...actionArgs.args]);
                    })()
                  : undefined;
                if (
                  $steps["invokeGlobalAction2"] != null &&
                  typeof $steps["invokeGlobalAction2"] === "object" &&
                  typeof $steps["invokeGlobalAction2"].then === "function"
                ) {
                  $steps["invokeGlobalAction2"] = await $steps[
                    "invokeGlobalAction2"
                  ];
                }
              }}
              placeholderEmail={"Entrez votre email"}
              submitButtonStyle={"primary"}
              submitButtonText={"Réinitialiser"}
              title={"Mot de passe oublié ?"}
              titleHeading={"h1"}
              wrapperStyle={"card"}
            />
          </div>
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "freeBox",
    "logo",
    "imageLogo",
    "frame65",
    "rectangle136",
    "frame67",
    "rectangle137",
    "text",
    "forgotPasswordForm"
  ],
  freeBox: [
    "freeBox",
    "logo",
    "imageLogo",
    "frame65",
    "rectangle136",
    "frame67",
    "rectangle137",
    "text",
    "forgotPasswordForm"
  ],
  logo: [
    "logo",
    "imageLogo",
    "frame65",
    "rectangle136",
    "frame67",
    "rectangle137",
    "text"
  ],
  imageLogo: [
    "imageLogo",
    "frame65",
    "rectangle136",
    "frame67",
    "rectangle137"
  ],
  frame65: ["frame65", "rectangle136"],
  rectangle136: ["rectangle136"],
  frame67: ["frame67", "rectangle137"],
  rectangle137: ["rectangle137"],
  text: ["text"],
  forgotPasswordForm: ["forgotPasswordForm"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  root: "div";
  freeBox: "div";
  logo: "div";
  imageLogo: "div";
  frame65: "div";
  rectangle136: "div";
  frame67: "div";
  rectangle137: "div";
  text: "div";
  forgotPasswordForm: typeof ForgotPassword;
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicForgotPassword__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicForgotPassword__VariantsArgs;
    args?: PlasmicForgotPassword__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicForgotPassword__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicForgotPassword__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicForgotPassword__ArgProps,
          internalVariantPropNames: PlasmicForgotPassword__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicForgotPassword__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicForgotPassword";
  } else {
    func.displayName = `PlasmicForgotPassword.${nodeName}`;
  }
  return func;
}

export const PlasmicForgotPassword = Object.assign(
  // Top-level PlasmicForgotPassword renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    freeBox: makeNodeComponent("freeBox"),
    logo: makeNodeComponent("logo"),
    imageLogo: makeNodeComponent("imageLogo"),
    frame65: makeNodeComponent("frame65"),
    rectangle136: makeNodeComponent("rectangle136"),
    frame67: makeNodeComponent("frame67"),
    rectangle137: makeNodeComponent("rectangle137"),
    text: makeNodeComponent("text"),
    forgotPasswordForm: makeNodeComponent("forgotPasswordForm"),

    // Metadata about props expected for PlasmicForgotPassword
    internalVariantProps: PlasmicForgotPassword__VariantProps,
    internalArgProps: PlasmicForgotPassword__ArgProps,

    // Page metadata
    pageMetadata: {
      title: "Mot de passe oublié",
      description: "",
      ogImageSrc: "",
      canonical: ""
    }
  }
);

export default PlasmicForgotPassword;
/* prettier-ignore-end */
