/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 341WB3S6fAjbZggAzyKhr1
// Component: AY28a70OS2RI

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import { usePlasmicDataSourceContext } from "@plasmicapp/data-sources-context";
import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import Modal from "../../Modal"; // plasmic-import: 2dhqWpUZxzEb/component
import { FormWrapper } from "@plasmicpkgs/antd5/skinny/Form";
import { formHelpers as FormWrapper_Helpers } from "@plasmicpkgs/antd5/skinny/Form";
import { FormItemWrapper } from "@plasmicpkgs/antd5/skinny/FormItem";
import { AntdInput } from "@plasmicpkgs/antd5/skinny/registerInput";
import { inputHelpers as AntdInput_Helpers } from "@plasmicpkgs/antd5/skinny/registerInput";
import Button from "../../Button"; // plasmic-import: lcnlii-Mi9bF/component

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 341WB3S6fAjbZggAzyKhr1/projectcss
import sty from "./PlasmicCreateUpdateCompany.module.css"; // plasmic-import: AY28a70OS2RI/css

import LinkSimpleIcon from "./icons/PlasmicIcon__LinkSimple"; // plasmic-import: j1hFSwL8QFW8/icon
import XIcon from "./icons/PlasmicIcon__X"; // plasmic-import: Ciiq3-41nfH3/icon
import CircleIcon from "./icons/PlasmicIcon__Circle"; // plasmic-import: GXxwbmvNEgwq/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: t_DMhjzzg7u-/icon

createPlasmicElementProxy;

export type PlasmicCreateUpdateCompany__VariantMembers = {};
export type PlasmicCreateUpdateCompany__VariantsArgs = {};
type VariantPropType = keyof PlasmicCreateUpdateCompany__VariantsArgs;
export const PlasmicCreateUpdateCompany__VariantProps =
  new Array<VariantPropType>();

export type PlasmicCreateUpdateCompany__ArgsType = {
  open?: boolean;
  onOpenChange?: (val: string) => void;
  compId?: any;
  onCompIdChange?: (val: string) => void;
  mode?: string;
  onModeChange2?: (val: string) => void;
  clientId?: number;
};
type ArgPropType = keyof PlasmicCreateUpdateCompany__ArgsType;
export const PlasmicCreateUpdateCompany__ArgProps = new Array<ArgPropType>(
  "open",
  "onOpenChange",
  "compId",
  "onCompIdChange",
  "mode",
  "onModeChange2",
  "clientId"
);

export type PlasmicCreateUpdateCompany__OverridesType = {
  createUpdateCompany?: Flex__<typeof Modal>;
  frame1437254016?: Flex__<"div">;
  name?: Flex__<"div">;
  frame1437254019?: Flex__<"div">;
  form?: Flex__<typeof FormWrapper>;
  formField?: Flex__<typeof FormItemWrapper>;
  input?: Flex__<typeof AntdInput>;
  button?: Flex__<typeof Button>;
  freeBox?: Flex__<"div">;
};

export interface DefaultCreateUpdateCompanyProps {
  open?: boolean;
  onOpenChange?: (val: string) => void;
  compId?: any;
  onCompIdChange?: (val: string) => void;
  mode?: string;
  onModeChange2?: (val: string) => void;
  clientId?: number;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicCreateUpdateCompany__RenderFunc(props: {
  variants: PlasmicCreateUpdateCompany__VariantsArgs;
  args: PlasmicCreateUpdateCompany__ArgsType;
  overrides: PlasmicCreateUpdateCompany__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  const $globalActions = useGlobalActions?.();

  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "createUpdateCompany.isOpen",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $state.open;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })()
      },
      {
        path: "form.value",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        refName: "form",
        onMutate: generateOnMutateForSpec("value", FormWrapper_Helpers)
      },
      {
        path: "form.isSubmitting",
        type: "private",
        variableType: "boolean",
        initFunc: ({ $props, $state, $queries, $ctx }) => false,

        refName: "form",
        onMutate: generateOnMutateForSpec("isSubmitting", FormWrapper_Helpers)
      },
      {
        path: "input.value",
        type: "private",
        variableType: "text",
        initFunc: ({ $props, $state, $queries, $ctx }) => undefined,

        onMutate: generateOnMutateForSpec("value", AntdInput_Helpers)
      },
      {
        path: "open",
        type: "writable",
        variableType: "boolean",

        valueProp: "open",
        onChangeProp: "onOpenChange"
      },
      {
        path: "compId",
        type: "writable",
        variableType: "object",

        valueProp: "compId",
        onChangeProp: "onCompIdChange"
      },
      {
        path: "mode",
        type: "writable",
        variableType: "text",

        valueProp: "mode",
        onChangeProp: "onModeChange2"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: {},
    $refs
  });
  const dataSourcesCtx = usePlasmicDataSourceContext();
  const plasmicInvalidate = usePlasmicInvalidate();

  return (
    <Modal
      data-plasmic-name={"createUpdateCompany"}
      data-plasmic-override={overrides.createUpdateCompany}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.createUpdateCompany)}
      closeOnBackdropClick={false}
      content={(() => {
        const child$Props = {
          className: classNames("__wab_instance", sty.form),
          extendedOnValuesChange: async (...eventArgs: any) => {
            generateStateOnChangePropForCodeComponents(
              $state,
              "value",
              ["form", "value"],
              FormWrapper_Helpers
            ).apply(null, eventArgs);
          },
          formItems: [
            { label: "Name", name: "name", inputType: "Text" },
            { label: "Message", name: "message", inputType: "Text Area" }
          ],
          initialValues: (() => {
            try {
              return $state.mode === "update" ? $state.compId : null;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return undefined;
              }
              throw e;
            }
          })(),
          labelCol: { span: 8, horizontalOnly: true },
          layout: "vertical",
          mode: "advanced",
          onFinish: async values => {
            const $steps = {};

            $steps["create"] =
              $state.mode === "create"
                ? (() => {
                    const actionArgs = {
                      dataOp: {
                        sourceId: "v6umJuHyep6kPNyCAJjouT",
                        opId: "5bdc3ae2-1ac6-4643-b67f-a452e484b8c6",
                        userArgs: {
                          variables: [
                            $ctx.SupabaseUser.user == null
                              ? null
                              : $ctx.SupabaseUser.user.id,
                            $state.form.value.name,
                            $props.clientId
                          ]
                        },
                        cacheKey: null,
                        invalidatedKeys: [
                          "fd92312b-5865-4e9c-82b7-ea9ff49707f8"
                        ],
                        roleId: null
                      }
                    };
                    return (async ({ dataOp, continueOnError }) => {
                      try {
                        const response = await executePlasmicDataOp(dataOp, {
                          userAuthToken: dataSourcesCtx?.userAuthToken,
                          user: dataSourcesCtx?.user
                        });
                        await plasmicInvalidate(dataOp.invalidatedKeys);
                        return response;
                      } catch (e) {
                        if (!continueOnError) {
                          throw e;
                        }
                        return e;
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
            if (
              $steps["create"] != null &&
              typeof $steps["create"] === "object" &&
              typeof $steps["create"].then === "function"
            ) {
              $steps["create"] = await $steps["create"];
            }

            $steps["update"] =
              $state.mode === "update"
                ? (() => {
                    const actionArgs = {
                      dataOp: {
                        sourceId: "v6umJuHyep6kPNyCAJjouT",
                        opId: "f2e4c557-31f2-4bd1-92d5-85d35b5f8648",
                        userArgs: {
                          keys: [$state.compId.id],
                          variables: [
                            $ctx.SupabaseUser.user == undefined
                              ? null
                              : $ctx.SupabaseUser.user.id,
                            $state.form.value.name,
                            new Date().toISOString()
                          ]
                        },
                        cacheKey: null,
                        invalidatedKeys: [
                          "eed05c21-7f7f-4297-9c21-7c09331a4f7c"
                        ],
                        roleId: null
                      }
                    };
                    return (async ({ dataOp, continueOnError }) => {
                      try {
                        const response = await executePlasmicDataOp(dataOp, {
                          userAuthToken: dataSourcesCtx?.userAuthToken,
                          user: dataSourcesCtx?.user
                        });
                        await plasmicInvalidate(dataOp.invalidatedKeys);
                        return response;
                      } catch (e) {
                        if (!continueOnError) {
                          throw e;
                        }
                        return e;
                      }
                    })?.apply(null, [actionArgs]);
                  })()
                : undefined;
            if (
              $steps["update"] != null &&
              typeof $steps["update"] === "object" &&
              typeof $steps["update"].then === "function"
            ) {
              $steps["update"] = await $steps["update"];
            }

            $steps["invokeGlobalAction"] = true
              ? (() => {
                  const actionArgs = {
                    args: [
                      "success",
                      (() => {
                        try {
                          return $state.mode === "update"
                            ? "Société mise à jour"
                            : "Société créée";
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return undefined;
                          }
                          throw e;
                        }
                      })(),
                      undefined,
                      undefined,
                      "bottom"
                    ]
                  };
                  return $globalActions[
                    "plasmic-antd5-config-provider.showNotification"
                  ]?.apply(null, [...actionArgs.args]);
                })()
              : undefined;
            if (
              $steps["invokeGlobalAction"] != null &&
              typeof $steps["invokeGlobalAction"] === "object" &&
              typeof $steps["invokeGlobalAction"].then === "function"
            ) {
              $steps["invokeGlobalAction"] = await $steps["invokeGlobalAction"];
            }

            $steps["updateNewOperation"] = true
              ? (() => {
                  const actionArgs = {
                    operation: 0,
                    value: false,
                    variable: {
                      objRoot: $state,
                      variablePath: ["open"]
                    }
                  };
                  return (({ variable, value, startIndex, deleteCount }) => {
                    if (!variable) {
                      return;
                    }
                    const { objRoot, variablePath } = variable;

                    $stateSet(objRoot, variablePath, value);
                    return value;
                  })?.apply(null, [actionArgs]);
                })()
              : undefined;
            if (
              $steps["updateNewOperation"] != null &&
              typeof $steps["updateNewOperation"] === "object" &&
              typeof $steps["updateNewOperation"].then === "function"
            ) {
              $steps["updateNewOperation"] = await $steps["updateNewOperation"];
            }
          },
          onFinishFailed: async data => {
            const $steps = {};

            $steps["invokeGlobalAction"] = true
              ? (() => {
                  const actionArgs = {
                    args: ["error", "Erreur", ``, undefined, "bottom"]
                  };
                  return $globalActions[
                    "plasmic-antd5-config-provider.showNotification"
                  ]?.apply(null, [...actionArgs.args]);
                })()
              : undefined;
            if (
              $steps["invokeGlobalAction"] != null &&
              typeof $steps["invokeGlobalAction"] === "object" &&
              typeof $steps["invokeGlobalAction"].then === "function"
            ) {
              $steps["invokeGlobalAction"] = await $steps["invokeGlobalAction"];
            }
          },
          onIsSubmittingChange: async (...eventArgs: any) => {
            generateStateOnChangePropForCodeComponents(
              $state,
              "isSubmitting",
              ["form", "isSubmitting"],
              FormWrapper_Helpers
            ).apply(null, eventArgs);
          },
          ref: ref => {
            $refs["form"] = ref;
          },
          submitSlot: null,
          wrapperCol: { span: 16, horizontalOnly: true }
        };
        initializeCodeComponentStates(
          $state,
          [
            {
              name: "value",
              plasmicStateName: "form.value"
            },
            {
              name: "isSubmitting",
              plasmicStateName: "form.isSubmitting"
            }
          ],
          [],
          FormWrapper_Helpers ?? {},
          child$Props
        );

        return (
          <FormWrapper
            data-plasmic-name={"form"}
            data-plasmic-override={overrides.form}
            {...child$Props}
          >
            <FormItemWrapper
              data-plasmic-name={"formField"}
              data-plasmic-override={overrides.formField}
              className={classNames("__wab_instance", sty.formField)}
              initialValue={undefined}
              label={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text___12WFe
                  )}
                >
                  {"Nom soci\u00e9t\u00e9"}
                </div>
              }
              name={"name"}
              rules={[{ ruleType: "required", message: "Entreprise requise" }]}
            >
              {(() => {
                const child$Props = {
                  className: classNames("__wab_instance", sty.input),
                  onChange: async (...eventArgs: any) => {
                    generateStateOnChangePropForCodeComponents(
                      $state,
                      "value",
                      ["input", "value"],
                      AntdInput_Helpers
                    ).apply(null, eventArgs);
                  },
                  size: "large",
                  type: "text",
                  value: generateStateValueProp($state, ["input", "value"])
                };
                initializeCodeComponentStates(
                  $state,
                  [
                    {
                      name: "value",
                      plasmicStateName: "input.value"
                    }
                  ],
                  [],
                  AntdInput_Helpers ?? {},
                  child$Props
                );

                return (
                  <AntdInput
                    data-plasmic-name={"input"}
                    data-plasmic-override={overrides.input}
                    {...child$Props}
                  />
                );
              })()}
            </FormItemWrapper>
            <Button
              data-plasmic-name={"button"}
              data-plasmic-override={overrides.button}
              className={classNames("__wab_instance", sty.button)}
              label={
                <div
                  className={classNames(
                    projectcss.all,
                    projectcss.__wab_text,
                    sty.text__xCzpV
                  )}
                >
                  <React.Fragment>
                    {(() => {
                      try {
                        return $state.mode === "update"
                          ? "Mettre à jour"
                          : "Créer";
                      } catch (e) {
                        if (
                          e instanceof TypeError ||
                          e?.plasmicType === "PlasmicUndefinedDataError"
                        ) {
                          return "Cr\u00e9er";
                        }
                        throw e;
                      }
                    })()}
                  </React.Fragment>
                </div>
              }
              submitsForm={true}
            />
          </FormWrapper>
        );
      })()}
      footer={
        <div
          data-plasmic-name={"freeBox"}
          data-plasmic-override={overrides.freeBox}
          className={classNames(projectcss.all, sty.freeBox)}
        />
      }
      heading={
        <div
          data-plasmic-name={"frame1437254016"}
          data-plasmic-override={overrides.frame1437254016}
          className={classNames(projectcss.all, sty.frame1437254016)}
        >
          <div
            data-plasmic-name={"name"}
            data-plasmic-override={overrides.name}
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.name
            )}
          >
            <React.Fragment>
              {(() => {
                try {
                  return $state.mode === "update"
                    ? "Mettre à jour société"
                    : "Nouvelle société";
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return "Nouvelle prestation";
                  }
                  throw e;
                }
              })()}
            </React.Fragment>
          </div>
          <Stack__
            as={"div"}
            data-plasmic-name={"frame1437254019"}
            data-plasmic-override={overrides.frame1437254019}
            hasGap={true}
            className={classNames(projectcss.all, sty.frame1437254019)}
          >
            <LinkSimpleIcon
              className={classNames(projectcss.all, sty.svg__ur7SA)}
              role={"img"}
            />

            <XIcon
              className={classNames(projectcss.all, sty.svg___6PU74)}
              onClick={async event => {
                const $steps = {};

                $steps["updateNewOperation"] = true
                  ? (() => {
                      const actionArgs = {
                        operation: 0,
                        value: false,
                        variable: {
                          objRoot: $state,
                          variablePath: ["open"]
                        }
                      };
                      return (({
                        variable,
                        value,
                        startIndex,
                        deleteCount
                      }) => {
                        if (!variable) {
                          return;
                        }
                        const { objRoot, variablePath } = variable;

                        $stateSet(objRoot, variablePath, value);
                        return value;
                      })?.apply(null, [actionArgs]);
                    })()
                  : undefined;
                if (
                  $steps["updateNewOperation"] != null &&
                  typeof $steps["updateNewOperation"] === "object" &&
                  typeof $steps["updateNewOperation"].then === "function"
                ) {
                  $steps["updateNewOperation"] = await $steps[
                    "updateNewOperation"
                  ];
                }
              }}
              role={"img"}
            />
          </Stack__>
        </div>
      }
      isOpen={generateStateValueProp($state, ["createUpdateCompany", "isOpen"])}
      noTrigger={true}
      onOpenChange={async (...eventArgs: any) => {
        generateStateOnChangeProp($state, [
          "createUpdateCompany",
          "isOpen"
        ]).apply(null, eventArgs);

        if (
          eventArgs.length > 1 &&
          eventArgs[1] &&
          eventArgs[1]._plasmic_state_init_
        ) {
          return;
        }
      }}
      showFooter={false}
      trigger={null}
    />
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  createUpdateCompany: [
    "createUpdateCompany",
    "frame1437254016",
    "name",
    "frame1437254019",
    "form",
    "formField",
    "input",
    "button",
    "freeBox"
  ],
  frame1437254016: ["frame1437254016", "name", "frame1437254019"],
  name: ["name"],
  frame1437254019: ["frame1437254019"],
  form: ["form", "formField", "input", "button"],
  formField: ["formField", "input"],
  input: ["input"],
  button: ["button"],
  freeBox: ["freeBox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  createUpdateCompany: typeof Modal;
  frame1437254016: "div";
  name: "div";
  frame1437254019: "div";
  form: typeof FormWrapper;
  formField: typeof FormItemWrapper;
  input: typeof AntdInput;
  button: typeof Button;
  freeBox: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicCreateUpdateCompany__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicCreateUpdateCompany__VariantsArgs;
    args?: PlasmicCreateUpdateCompany__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicCreateUpdateCompany__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicCreateUpdateCompany__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicCreateUpdateCompany__ArgProps,
          internalVariantPropNames: PlasmicCreateUpdateCompany__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicCreateUpdateCompany__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "createUpdateCompany") {
    func.displayName = "PlasmicCreateUpdateCompany";
  } else {
    func.displayName = `PlasmicCreateUpdateCompany.${nodeName}`;
  }
  return func;
}

export const PlasmicCreateUpdateCompany = Object.assign(
  // Top-level PlasmicCreateUpdateCompany renders the root element
  makeNodeComponent("createUpdateCompany"),
  {
    // Helper components rendering sub-elements
    frame1437254016: makeNodeComponent("frame1437254016"),
    _name: makeNodeComponent("name"),
    frame1437254019: makeNodeComponent("frame1437254019"),
    form: makeNodeComponent("form"),
    formField: makeNodeComponent("formField"),
    input: makeNodeComponent("input"),
    button: makeNodeComponent("button"),
    freeBox: makeNodeComponent("freeBox"),

    // Metadata about props expected for PlasmicCreateUpdateCompany
    internalVariantProps: PlasmicCreateUpdateCompany__VariantProps,
    internalArgProps: PlasmicCreateUpdateCompany__ArgProps
  }
);

export default PlasmicCreateUpdateCompany;
/* prettier-ignore-end */
