/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 341WB3S6fAjbZggAzyKhr1
// Component: zu3ZCS3LfO6O

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import {
  executePlasmicDataOp,
  usePlasmicDataOp,
  usePlasmicInvalidate
} from "@plasmicapp/react-web/lib/data-sources";

import Checkbox from "../../Checkbox"; // plasmic-import: QA-Gc8H2apHJ/component
import { Fetcher } from "@plasmicapp/react-web/lib/data-sources";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 341WB3S6fAjbZggAzyKhr1/projectcss
import sty from "./PlasmicDataGridDispositif2.module.css"; // plasmic-import: zu3ZCS3LfO6O/css

import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: OJTnKg-tc1Dy/icon
import ChevronDownIcon from "./icons/PlasmicIcon__ChevronDown"; // plasmic-import: t_DMhjzzg7u-/icon

createPlasmicElementProxy;

export type PlasmicDataGridDispositif2__VariantMembers = {};
export type PlasmicDataGridDispositif2__VariantsArgs = {};
type VariantPropType = keyof PlasmicDataGridDispositif2__VariantsArgs;
export const PlasmicDataGridDispositif2__VariantProps =
  new Array<VariantPropType>();

export type PlasmicDataGridDispositif2__ArgsType = {
  pageNumber?: number;
  onPageNumberChange?: (val: string) => void;
  headerItems?: any;
  onHeaderItemsChange2?: (val: string) => void;
  clientId?: number;
};
type ArgPropType = keyof PlasmicDataGridDispositif2__ArgsType;
export const PlasmicDataGridDispositif2__ArgProps = new Array<ArgPropType>(
  "pageNumber",
  "onPageNumberChange",
  "headerItems",
  "onHeaderItemsChange2",
  "clientId"
);

export type PlasmicDataGridDispositif2__OverridesType = {
  dataGridDispositif?: Flex__<"div">;
  container?: Flex__<"div">;
  grid?: Flex__<"div">;
  header?: Flex__<"div">;
  list?: Flex__<"div">;
  checkbox?: Flex__<typeof Checkbox>;
  checkbox2?: Flex__<typeof Checkbox>;
  pagination?: Flex__<"div">;
  emptyDataMsg?: Flex__<"div">;
};

export interface DefaultDataGridDispositif2Props {
  pageNumber?: number;
  onPageNumberChange?: (val: string) => void;
  headerItems?: any;
  onHeaderItemsChange2?: (val: string) => void;
  clientId?: number;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicDataGridDispositif2__RenderFunc(props: {
  variants: PlasmicDataGridDispositif2__VariantsArgs;
  args: PlasmicDataGridDispositif2__ArgsType;
  overrides: PlasmicDataGridDispositif2__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {
          clientId: 1
        },
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  let [$queries, setDollarQueries] = React.useState<
    Record<string, ReturnType<typeof usePlasmicDataOp>>
  >({});
  const stateSpecs: Parameters<typeof useDollarState>[0] = React.useMemo(
    () => [
      {
        path: "pageNumber",
        type: "writable",
        variableType: "number",

        valueProp: "pageNumber",
        onChangeProp: "onPageNumberChange"
      },
      {
        path: "headerItems",
        type: "writable",
        variableType: "object",

        valueProp: "headerItems",
        onChangeProp: "onHeaderItemsChange2"
      },
      {
        path: "dataObject",
        type: "private",
        variableType: "object",
        initFunc: ({ $props, $state, $queries, $ctx }) =>
          (() => {
            try {
              return $queries.rtxDispositif.data;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return {};
              }
              throw e;
            }
          })()
      },
      {
        path: "checkbox[].isSelected",
        type: "private",
        variableType: "boolean"
      },
      {
        path: "checkbox2[].isSelected",
        type: "private",
        variableType: "boolean"
      }
    ],
    [$props, $ctx, $refs]
  );
  const $state = useDollarState(stateSpecs, {
    $props,
    $ctx,
    $queries: $queries,
    $refs
  });

  const new$Queries: Record<string, ReturnType<typeof usePlasmicDataOp>> = {
    rtxDispositif: usePlasmicDataOp(() => {
      return {
        sourceId: "v6umJuHyep6kPNyCAJjouT",
        opId: "069e9c41-c976-4aab-bc58-904cf4e3c2f9",
        userArgs: {
          query: [$props.clientId]
        },
        cacheKey: `plasmic.$.069e9c41-c976-4aab-bc58-904cf4e3c2f9.$.`,
        invalidatedKeys: null,
        roleId: null
      };
    })
  };
  if (Object.keys(new$Queries).some(k => new$Queries[k] !== $queries[k])) {
    setDollarQueries(new$Queries);

    $queries = new$Queries;
  }

  return (
    <div
      data-plasmic-name={"dataGridDispositif"}
      data-plasmic-override={overrides.dataGridDispositif}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.dataGridDispositif
      )}
    >
      {(() => {
        try {
          return $queries.rtxDispositif?.data?.length > 0;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div
          data-plasmic-name={"container"}
          data-plasmic-override={overrides.container}
          className={classNames(projectcss.all, sty.container)}
        >
          <div
            data-plasmic-name={"grid"}
            data-plasmic-override={overrides.grid}
            className={classNames(projectcss.all, sty.grid)}
          >
            <div className={classNames(projectcss.all, sty.freeBox__uu8Rb)}>
              <div
                data-plasmic-name={"header"}
                data-plasmic-override={overrides.header}
                className={classNames(projectcss.all, sty.header)}
              >
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__g2Md3)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6T5Sc
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[0].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Nom";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__rnui7)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateDataObject"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dataObject"]
                              },
                              operation: 0,
                              value: $queries.rtxDispositif.data.sort((a, b) =>
                                a.main_mission.localeCompare(b.main_mission)
                              )
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDataObject"] != null &&
                        typeof $steps["updateDataObject"] === "object" &&
                        typeof $steps["updateDataObject"].then === "function"
                      ) {
                        $steps["updateDataObject"] = await $steps[
                          "updateDataObject"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__sSx9Z)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ynUQa
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[1].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Type";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
                <div
                  className={classNames(projectcss.all, sty.freeBox___6Y89N)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___6Motg
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[2].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Actions";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__kcCf7)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__ar54
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[3].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Statut";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__kF8Ab)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateDataObject"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dataObject"]
                              },
                              operation: 0,
                              value: $queries.rtxDispositif.data.sort((a, b) =>
                                a.position_name.localeCompare(b.position_name)
                              )
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDataObject"] != null &&
                        typeof $steps["updateDataObject"] === "object" &&
                        typeof $steps["updateDataObject"].then === "function"
                      ) {
                        $steps["updateDataObject"] = await $steps[
                          "updateDataObject"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__o0Yla)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__qBtfd
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[4].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Heures Dispositif";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__sqG2L)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateDataObject"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dataObject"]
                              },
                              operation: 0,
                              value: $queries.rtxDispositif.data.sort((a, b) =>
                                a.company_id.localeCompare(b.company_id)
                              )
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDataObject"] != null &&
                        typeof $steps["updateDataObject"] === "object" &&
                        typeof $steps["updateDataObject"].then === "function"
                      ) {
                        $steps["updateDataObject"] = await $steps[
                          "updateDataObject"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                </Stack__>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox___1LxGm)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__y6Kz1
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[5].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Heures Dispositif";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__a4Vk8)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateDataObject"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dataObject"]
                              },
                              operation: 0,
                              value: $queries.rtxDispositif.data.sort((a, b) =>
                                a.company_id.localeCompare(b.company_id)
                              )
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDataObject"] != null &&
                        typeof $steps["updateDataObject"] === "object" &&
                        typeof $steps["updateDataObject"].then === "function"
                      ) {
                        $steps["updateDataObject"] = await $steps[
                          "updateDataObject"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__krh9K)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__fn5XR
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[6].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Date de d\u00e9but";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__tfDb)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__sScne
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[5].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Budget (k\u20ac)";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__mOgB3)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateDataObject"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dataObject"]
                              },
                              operation: 0,
                              value: $queries.rtxDispositif.data.sort(
                                (a, b) => a.total_price - b.total_price
                              )
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDataObject"] != null &&
                        typeof $steps["updateDataObject"] === "object" &&
                        typeof $steps["updateDataObject"].then === "function"
                      ) {
                        $steps["updateDataObject"] = await $steps[
                          "updateDataObject"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                </Stack__>
                <div className={classNames(projectcss.all, sty.freeBox__ylRis)}>
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text__s3GEt
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[7].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Actions";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                </div>
                <Stack__
                  as={"div"}
                  hasGap={true}
                  className={classNames(projectcss.all, sty.freeBox__xeY5E)}
                >
                  <div
                    className={classNames(
                      projectcss.all,
                      projectcss.__wab_text,
                      sty.text___9WBCf
                    )}
                  >
                    <React.Fragment>
                      {(() => {
                        try {
                          return $state.headerItems[7].name;
                        } catch (e) {
                          if (
                            e instanceof TypeError ||
                            e?.plasmicType === "PlasmicUndefinedDataError"
                          ) {
                            return "Heures Dispositif";
                          }
                          throw e;
                        }
                      })()}
                    </React.Fragment>
                  </div>
                  <Icon3Icon
                    className={classNames(projectcss.all, sty.svg__vrTn9)}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updateDataObject"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["dataObject"]
                              },
                              operation: 0,
                              value: $queries.rtxDispositif.data.sort((a, b) =>
                                a.company_id.localeCompare(b.company_id)
                              )
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updateDataObject"] != null &&
                        typeof $steps["updateDataObject"] === "object" &&
                        typeof $steps["updateDataObject"].then === "function"
                      ) {
                        $steps["updateDataObject"] = await $steps[
                          "updateDataObject"
                        ];
                      }
                    }}
                    role={"img"}
                  />
                </Stack__>
              </div>
              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                (() => {
                  try {
                    return (() => {
                      const data = $state.dataObject;
                      const currentPage = $state.pageNumber;
                      const pageSize = 8;
                      const paginatedData = data.slice(
                        (currentPage - 1) * pageSize,
                        currentPage * pageSize
                      );
                      return paginatedData;
                    })();
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [];
                    }
                    throw e;
                  }
                })()
              ).map((__plasmic_item_0, __plasmic_idx_0) => {
                const currentItem = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <div
                    data-plasmic-name={"list"}
                    data-plasmic-override={overrides.list}
                    className={classNames(projectcss.all, sty.list)}
                    key={currentIndex}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1X8Ru
                      )}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text___9IeVn
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.main_mission;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__ljyuK)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nM3GQ
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.task_id;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__fHxOn)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__aemVo
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.date_start;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__kXnKk)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qKjGh
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.position_name;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox___0Vxs)}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames("__wab_instance", sty.checkbox),
                          isSelected: generateStateValueProp($state, [
                            "checkbox",
                            __plasmic_idx_0,
                            "isSelected"
                          ]),
                          label: (
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__fytIg
                              )}
                            >
                              {"Option"}
                            </div>
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "checkbox",
                              __plasmic_idx_0,
                              "isSelected"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }
                        };

                        initializePlasmicStates(
                          $state,
                          [
                            {
                              name: "checkbox[].isSelected",
                              initFunc: ({ $props, $state, $queries }) => false
                            }
                          ],
                          [__plasmic_idx_0]
                        );
                        return (
                          <Checkbox
                            data-plasmic-name={"checkbox"}
                            data-plasmic-override={overrides.checkbox}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                    <div
                      className={classNames(
                        projectcss.all,
                        sty.freeBox___1FSoY
                      )}
                    >
                      {(() => {
                        const child$Props = {
                          className: classNames(
                            "__wab_instance",
                            sty.checkbox2
                          ),
                          isSelected: generateStateValueProp($state, [
                            "checkbox2",
                            __plasmic_idx_0,
                            "isSelected"
                          ]),
                          label: (
                            <div
                              className={classNames(
                                projectcss.all,
                                projectcss.__wab_text,
                                sty.text__oWd9V
                              )}
                            >
                              {"Option"}
                            </div>
                          ),
                          onChange: async (...eventArgs: any) => {
                            generateStateOnChangeProp($state, [
                              "checkbox2",
                              __plasmic_idx_0,
                              "isSelected"
                            ]).apply(null, eventArgs);

                            if (
                              eventArgs.length > 1 &&
                              eventArgs[1] &&
                              eventArgs[1]._plasmic_state_init_
                            ) {
                              return;
                            }
                          }
                        };

                        initializePlasmicStates(
                          $state,
                          [
                            {
                              name: "checkbox2[].isSelected",
                              initFunc: ({ $props, $state, $queries }) => false
                            }
                          ],
                          [__plasmic_idx_0]
                        );
                        return (
                          <Checkbox
                            data-plasmic-name={"checkbox2"}
                            data-plasmic-override={overrides.checkbox2}
                            {...child$Props}
                          />
                        );
                      })()}
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox__g536N)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__qntYx
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.description;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                    <div
                      className={classNames(projectcss.all, sty.freeBox___6ML)}
                    >
                      <div
                        className={classNames(
                          projectcss.all,
                          projectcss.__wab_text,
                          sty.text__nVvhH
                        )}
                      >
                        <React.Fragment>
                          {(() => {
                            try {
                              return currentItem.company_id;
                            } catch (e) {
                              if (
                                e instanceof TypeError ||
                                e?.plasmicType === "PlasmicUndefinedDataError"
                              ) {
                                return "";
                              }
                              throw e;
                            }
                          })()}
                        </React.Fragment>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          </div>
          {(() => {
            try {
              return $state.dataObject.length > 8;
            } catch (e) {
              if (
                e instanceof TypeError ||
                e?.plasmicType === "PlasmicUndefinedDataError"
              ) {
                return true;
              }
              throw e;
            }
          })() ? (
            <Stack__
              as={"div"}
              data-plasmic-name={"pagination"}
              data-plasmic-override={overrides.pagination}
              hasGap={true}
              className={classNames(projectcss.all, sty.pagination)}
            >
              {(() => {
                try {
                  return $state.pageNumber > 1;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <ChevronDownIcon
                  className={classNames(projectcss.all, sty.svg__hbOdc)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updatePageNumber"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["pageNumber"]
                            },
                            operation: 3
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = $stateGet(objRoot, variablePath);
                            $stateSet(objRoot, variablePath, oldValue - 1);
                            return oldValue - 1;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updatePageNumber"] != null &&
                      typeof $steps["updatePageNumber"] === "object" &&
                      typeof $steps["updatePageNumber"].then === "function"
                    ) {
                      $steps["updatePageNumber"] = await $steps[
                        "updatePageNumber"
                      ];
                    }
                  }}
                  role={"img"}
                />
              ) : null}
              {(_par => (!_par ? [] : Array.isArray(_par) ? _par : [_par]))(
                (() => {
                  try {
                    return (() => {
                      const itemsPerPage = 8;
                      const data = $queries.rtxDispositif.data;
                      const pageCount = Math.ceil(data.length / itemsPerPage);
                      const paginationArray = Array.from(
                        { length: pageCount },
                        (_, i) => i + 1
                      );
                      return paginationArray;
                    })();
                  } catch (e) {
                    if (
                      e instanceof TypeError ||
                      e?.plasmicType === "PlasmicUndefinedDataError"
                    ) {
                      return [];
                    }
                    throw e;
                  }
                })()
              ).map((__plasmic_item_0, __plasmic_idx_0) => {
                const currentItem = __plasmic_item_0;
                const currentIndex = __plasmic_idx_0;
                return (
                  <div
                    className={classNames(projectcss.all, sty.freeBox__xvq0W)}
                    key={currentIndex}
                    onClick={async event => {
                      const $steps = {};

                      $steps["updatePageNumber"] = true
                        ? (() => {
                            const actionArgs = {
                              variable: {
                                objRoot: $state,
                                variablePath: ["pageNumber"]
                              },
                              operation: 0,
                              value: currentItem
                            };
                            return (({
                              variable,
                              value,
                              startIndex,
                              deleteCount
                            }) => {
                              if (!variable) {
                                return;
                              }
                              const { objRoot, variablePath } = variable;

                              $stateSet(objRoot, variablePath, value);
                              return value;
                            })?.apply(null, [actionArgs]);
                          })()
                        : undefined;
                      if (
                        $steps["updatePageNumber"] != null &&
                        typeof $steps["updatePageNumber"] === "object" &&
                        typeof $steps["updatePageNumber"].then === "function"
                      ) {
                        $steps["updatePageNumber"] = await $steps[
                          "updatePageNumber"
                        ];
                      }
                    }}
                  >
                    <div
                      className={classNames(
                        projectcss.all,
                        projectcss.__wab_text,
                        sty.text___3Ejpa
                      )}
                      onClick={async event => {
                        const $steps = {};
                      }}
                    >
                      <React.Fragment>
                        {(() => {
                          try {
                            return currentItem;
                          } catch (e) {
                            if (
                              e instanceof TypeError ||
                              e?.plasmicType === "PlasmicUndefinedDataError"
                            ) {
                              return "";
                            }
                            throw e;
                          }
                        })()}
                      </React.Fragment>
                    </div>
                  </div>
                );
              })}
              {(() => {
                try {
                  return $queries.rtxDispositif?.data?.length > 8;
                } catch (e) {
                  if (
                    e instanceof TypeError ||
                    e?.plasmicType === "PlasmicUndefinedDataError"
                  ) {
                    return true;
                  }
                  throw e;
                }
              })() ? (
                <ChevronDownIcon
                  className={classNames(projectcss.all, sty.svg__vzKx8)}
                  onClick={async event => {
                    const $steps = {};

                    $steps["updatePageNumber"] = true
                      ? (() => {
                          const actionArgs = {
                            variable: {
                              objRoot: $state,
                              variablePath: ["pageNumber"]
                            },
                            operation: 2
                          };
                          return (({
                            variable,
                            value,
                            startIndex,
                            deleteCount
                          }) => {
                            if (!variable) {
                              return;
                            }
                            const { objRoot, variablePath } = variable;

                            const oldValue = $stateGet(objRoot, variablePath);
                            $stateSet(objRoot, variablePath, oldValue + 1);
                            return oldValue + 1;
                          })?.apply(null, [actionArgs]);
                        })()
                      : undefined;
                    if (
                      $steps["updatePageNumber"] != null &&
                      typeof $steps["updatePageNumber"] === "object" &&
                      typeof $steps["updatePageNumber"].then === "function"
                    ) {
                      $steps["updatePageNumber"] = await $steps[
                        "updatePageNumber"
                      ];
                    }
                  }}
                  role={"img"}
                />
              ) : null}
            </Stack__>
          ) : null}
        </div>
      ) : null}
      {(() => {
        try {
          return $queries.rtxDispositif?.data?.length == 0;
        } catch (e) {
          if (
            e instanceof TypeError ||
            e?.plasmicType === "PlasmicUndefinedDataError"
          ) {
            return true;
          }
          throw e;
        }
      })() ? (
        <div
          data-plasmic-name={"emptyDataMsg"}
          data-plasmic-override={overrides.emptyDataMsg}
          className={classNames(projectcss.all, sty.emptyDataMsg)}
        >
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text__ohpA5
            )}
          >
            {"Aucune donn\u00e9es trouv\u00e9es"}
          </div>
        </div>
      ) : null}
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  dataGridDispositif: [
    "dataGridDispositif",
    "container",
    "grid",
    "header",
    "list",
    "checkbox",
    "checkbox2",
    "pagination",
    "emptyDataMsg"
  ],
  container: [
    "container",
    "grid",
    "header",
    "list",
    "checkbox",
    "checkbox2",
    "pagination"
  ],
  grid: ["grid", "header", "list", "checkbox", "checkbox2"],
  header: ["header"],
  list: ["list", "checkbox", "checkbox2"],
  checkbox: ["checkbox"],
  checkbox2: ["checkbox2"],
  pagination: ["pagination"],
  emptyDataMsg: ["emptyDataMsg"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  dataGridDispositif: "div";
  container: "div";
  grid: "div";
  header: "div";
  list: "div";
  checkbox: typeof Checkbox;
  checkbox2: typeof Checkbox;
  pagination: "div";
  emptyDataMsg: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicDataGridDispositif2__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicDataGridDispositif2__VariantsArgs;
    args?: PlasmicDataGridDispositif2__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicDataGridDispositif2__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicDataGridDispositif2__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicDataGridDispositif2__ArgProps,
          internalVariantPropNames: PlasmicDataGridDispositif2__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicDataGridDispositif2__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "dataGridDispositif") {
    func.displayName = "PlasmicDataGridDispositif2";
  } else {
    func.displayName = `PlasmicDataGridDispositif2.${nodeName}`;
  }
  return func;
}

export const PlasmicDataGridDispositif2 = Object.assign(
  // Top-level PlasmicDataGridDispositif2 renders the root element
  makeNodeComponent("dataGridDispositif"),
  {
    // Helper components rendering sub-elements
    container: makeNodeComponent("container"),
    grid: makeNodeComponent("grid"),
    header: makeNodeComponent("header"),
    list: makeNodeComponent("list"),
    checkbox: makeNodeComponent("checkbox"),
    checkbox2: makeNodeComponent("checkbox2"),
    pagination: makeNodeComponent("pagination"),
    emptyDataMsg: makeNodeComponent("emptyDataMsg"),

    // Metadata about props expected for PlasmicDataGridDispositif2
    internalVariantProps: PlasmicDataGridDispositif2__VariantProps,
    internalArgProps: PlasmicDataGridDispositif2__ArgProps
  }
);

export default PlasmicDataGridDispositif2;
/* prettier-ignore-end */
