/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: 341WB3S6fAjbZggAzyKhr1
// Component: 15sK7-TYJ3_o

import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";
import { useRouter } from "next/router";

import {
  Flex as Flex__,
  MultiChoiceArg,
  PlasmicDataSourceContextProvider as PlasmicDataSourceContextProvider__,
  PlasmicIcon as PlasmicIcon__,
  PlasmicImg as PlasmicImg__,
  PlasmicLink as PlasmicLink__,
  PlasmicPageGuard as PlasmicPageGuard__,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  Stack as Stack__,
  StrictProps,
  Trans as Trans__,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
  generateOnMutateForSpec,
  generateStateOnChangeProp,
  generateStateOnChangePropForCodeComponents,
  generateStateValueProp,
  get as $stateGet,
  hasVariant,
  initializeCodeComponentStates,
  initializePlasmicStates,
  makeFragment,
  omit,
  pick,
  renderPlasmicSlot,
  set as $stateSet,
  useCurrentUser,
  useDollarState,
  usePlasmicTranslator,
  useTrigger,
  wrapWithClassName
} from "@plasmicapp/react-web";
import {
  DataCtxReader as DataCtxReader__,
  useDataEnv,
  useGlobalActions
} from "@plasmicapp/react-web/lib/host";

import "@plasmicapp/react-web/lib/plasmic.css";

import plasmic_antd_5_hostless_css from "../antd_5_hostless/plasmic.module.css"; // plasmic-import: ohDidvG9XsCeFumugENU3J/projectcss
import projectcss from "./plasmic.module.css"; // plasmic-import: 341WB3S6fAjbZggAzyKhr1/projectcss
import sty from "./PlasmicSaveModifButton.module.css"; // plasmic-import: 15sK7-TYJ3_o/css

import FloppyDiskBack2Icon from "./icons/PlasmicIcon__FloppyDiskBack2"; // plasmic-import: VuTfqiibFshI/icon

createPlasmicElementProxy;

export type PlasmicSaveModifButton__VariantMembers = {};
export type PlasmicSaveModifButton__VariantsArgs = {};
type VariantPropType = keyof PlasmicSaveModifButton__VariantsArgs;
export const PlasmicSaveModifButton__VariantProps =
  new Array<VariantPropType>();

export type PlasmicSaveModifButton__ArgsType = { submitsForm?: boolean };
type ArgPropType = keyof PlasmicSaveModifButton__ArgsType;
export const PlasmicSaveModifButton__ArgProps = new Array<ArgPropType>(
  "submitsForm"
);

export type PlasmicSaveModifButton__OverridesType = {
  buttonBase?: Flex__<"button">;
  svg?: Flex__<"svg">;
  text?: Flex__<"div">;
};

export interface DefaultSaveModifButtonProps {
  submitsForm?: boolean;
  className?: string;
}

const $$ = {};

function useNextRouter() {
  try {
    return useRouter();
  } catch {}
  return undefined;
}

function PlasmicSaveModifButton__RenderFunc(props: {
  variants: PlasmicSaveModifButton__VariantsArgs;
  args: PlasmicSaveModifButton__ArgsType;
  overrides: PlasmicSaveModifButton__OverridesType;
  forNode?: string;
}) {
  const { variants, overrides, forNode } = props;

  const args = React.useMemo(
    () =>
      Object.assign(
        {},
        Object.fromEntries(
          Object.entries(props.args).filter(([_, v]) => v !== undefined)
        )
      ),
    [props.args]
  );

  const $props = {
    ...args,
    ...variants
  };

  const __nextRouter = useNextRouter();

  const $ctx = useDataEnv?.() || {};
  const refsRef = React.useRef({});
  const $refs = refsRef.current;

  return (
    <Stack__
      as={"button"}
      data-plasmic-name={"buttonBase"}
      data-plasmic-override={overrides.buttonBase}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      hasGap={true}
      className={classNames(
        projectcss.all,
        projectcss.button,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        plasmic_antd_5_hostless_css.plasmic_tokens,
        sty.buttonBase
      )}
      ref={ref => {
        $refs["buttonBase"] = ref;
      }}
    >
      <FloppyDiskBack2Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(projectcss.all, sty.svg)}
        role={"img"}
      />

      <div
        data-plasmic-name={"text"}
        data-plasmic-override={overrides.text}
        className={classNames(projectcss.all, projectcss.__wab_text, sty.text)}
      >
        {"Sauvegarder la modification"}
      </div>
    </Stack__>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  buttonBase: ["buttonBase", "svg", "text"],
  svg: ["svg"],
  text: ["text"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  (typeof PlasmicDescendants)[T][number];
type NodeDefaultElementType = {
  buttonBase: "button";
  svg: "svg";
  text: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicSaveModifButton__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicSaveModifButton__VariantsArgs;
    args?: PlasmicSaveModifButton__ArgsType;
    overrides?: NodeOverridesType<T>;
  } & Omit<PlasmicSaveModifButton__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicSaveModifButton__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = React.useMemo(
      () =>
        deriveRenderOpts(props, {
          name: nodeName,
          descendantNames: PlasmicDescendants[nodeName],
          internalArgPropNames: PlasmicSaveModifButton__ArgProps,
          internalVariantPropNames: PlasmicSaveModifButton__VariantProps
        }),
      [props, nodeName]
    );
    return PlasmicSaveModifButton__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "buttonBase") {
    func.displayName = "PlasmicSaveModifButton";
  } else {
    func.displayName = `PlasmicSaveModifButton.${nodeName}`;
  }
  return func;
}

export const PlasmicSaveModifButton = Object.assign(
  // Top-level PlasmicSaveModifButton renders the root element
  makeNodeComponent("buttonBase"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    text: makeNodeComponent("text"),

    // Metadata about props expected for PlasmicSaveModifButton
    internalVariantProps: PlasmicSaveModifButton__VariantProps,
    internalArgProps: PlasmicSaveModifButton__ArgProps
  }
);

export default PlasmicSaveModifButton;
/* prettier-ignore-end */
